ARG PHP_VERSION
FROM registry.gitlab.com/flagstudio/laraflag:php-${PHP_VERSION}-base


###########################################################################
# Configs
###########################################################################


COPY ./docker/app/laraflag.ini /usr/local/etc/php/conf.d
COPY ./docker/app/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY ./docker/app/supervisord_local.conf /etc/supervisord.conf
COPY ./docker/app/Caddyfile /etc/Caddyfile
COPY ./docker/app/crontab /etc/crontabs/root


###########################################################################
# Opcache:
###########################################################################

ARG PHP_FPM_INSTALL_OPCACHE=true

RUN if [ ${PHP_FPM_INSTALL_OPCACHE} = true ]; then \
    docker-php-ext-install opcache \
;fi

# Copy opcache configration
COPY ./docker/app/opcache.ini /usr/local/etc/php/conf.d/opcache.ini

###########################################################################
# xDebug:
###########################################################################

ARG PHP_FPM_INSTALL_XDEBUG=false

RUN if [ ${PHP_FPM_INSTALL_XDEBUG} = true ]; then \
#    apk add --no-cache $PHPIZE_DEPS \
      pecl install xdebug \
      && docker-php-ext-enable xdebug \
    ;fi

# Copy xdebug configuration for remote debugging
COPY ./docker/app/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

###########################################################################
# Copy code
###########################################################################

#USER www-data:www-data
#COPY . /var/www/

###########################################################################
# Composer packages
###########################################################################

#USER root
#
#RUN composer install --optimize-autoloader --no-dev --no-scripts
#RUN composer dumpautoload

###########################################################################
# NPM
###########################################################################

#RUN npm i
#RUN npm run prod

###########################################################################
# Prepare Laravel for Prod
###########################################################################

#RUN php artisan package:discover
#RUN php artisan storage:link
#RUN php artisan route:cache
#
WORKDIR /var/www

CMD ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisord.conf"]

EXPOSE 8080 9000
