ARG PHP_VERSION
FROM registry.gitlab.com/flagstudio/laraflag:php-${PHP_VERSION}-base-debian


###########################################################################
# Configs
###########################################################################


COPY ./docker/app/laraflag.ini /usr/local/etc/php/conf.d
COPY ./docker/app/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY ./docker/app/supervisord_build.conf /etc/supervisord.conf
COPY ./docker/app/Caddyfile /etc/Caddyfile
COPY ./docker/app/crontab /var/spool/cron/crontabs/root
RUN crontab /var/spool/cron/crontabs/root

###########################################################################
# Opcache:
###########################################################################

ARG PHP_FPM_INSTALL_OPCACHE=true

RUN if [ ${PHP_FPM_INSTALL_OPCACHE} = true ]; then \
    docker-php-ext-install opcache \
;fi

# Copy opcache configration
COPY ./docker/app/opcache.ini /usr/local/etc/php/conf.d/opcache.ini

###########################################################################
# Postgresql client:
###########################################################################
RUN set -eux; \
    apt-get update --allow-releaseinfo-change; \
    apt-get upgrade -y; \
    apt-get install -y --no-install-recommends \
        lsb-release \
        libc6 \
        libtinfo6 \
        readline-common \
        libreadline-dev \
        libpq-dev \
        wget \
        gnupg2;

RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | tee  /etc/apt/sources.list.d/pgdg.list

RUN apt-get update --allow-releaseinfo-change -qq && apt-get install -y \
  postgresql-client-12;

###########################################################################
# Copy code
###########################################################################

USER www-data:www-data
COPY . /var/www/

###########################################################################
# Composer packages
###########################################################################

WORKDIR /var/www
USER root

RUN composer install --optimize-autoloader --no-dev --no-scripts
RUN composer dumpautoload

###########################################################################
# NPM
###########################################################################

RUN npm i
RUN npm run prod

###########################################################################
# Prepare Laravel for Prod
###########################################################################

RUN php artisan package:discover
RUN php artisan storage:link
RUN php artisan route:cache

# Micro Editor https://micro-editor.github.io/
RUN curl https://getmic.ro | bash; \
        mv micro /root/micro; \
        echo 'alias m="~/micro"' >> /root/.bashrc

CMD ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisord.conf"]

EXPOSE 8080
