version: '3'

services:

  ### APP (PHP-FPM + CADDY) ##############################################
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app_local
    build:
      args:
        - PHP_VERSION=7.4
        - PHP_FPM_INSTALL_XDEBUG=true
        - PHP_FPM_INSTALL_OPCACHE=false
      context: .
      dockerfile: docker/app/Dockerfile
    image: registry.gitlab.com/flagstudio/${COMPOSE_PROJECT_NAME}:latest # образ, который строим. НЕ ТОТ из которого строимся
    volumes:
      - ./:/var/www
    ports:
      - "8080:8080"


  ### SSL proxy (Caddy Server) #########################################
  ssl:
    image: registry.gitlab.com/flagstudio/laraflag:ssl-base
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./Caddyfile_SSL:/etc/Caddyfile


  ### MySQL ################################################
  mysql:
    image: registry.gitlab.com/flagstudio/laraflag:mysql-5.7-base
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    restart: always


  ### PostgreSQL ###########################################
  postgres:
    image: postgres:alpine
    command: postgres
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
