version: '3'

services:

  ### APP (PHP-FPM + CADDY) ##############################################
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app_local
    build:
      args:
        - PHP_VERSION=7.4
        - PHP_FPM_INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
        - PHP_FPM_INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
      context: .
      dockerfile: docker/app/Dockerfile_local
    image: registry.gitlab.com/flagstudio/${COMPOSE_PROJECT_NAME}:latest # образ, который строим. НЕ ТОТ из которого строимся
    volumes:
      - ./:/var/www
    ports:
      - "80:8080"
    expose:
      - "9000"

  ### SSL proxy (Caddy Server) #########################################
#  ssl:
#    image: registry.gitlab.com/flagstudio/laraflag:ssl-base
#    ports:
#      - "443:443"
#      - "80:80"
#    volumes:
#      - ./docker/ssl/Caddyfile_SSL:/etc/Caddyfile


  ### MySQL ################################################
  mysql:
    image: registry.gitlab.com/flagstudio/laraflag:mysql-5.7-base
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    restart: always


  ### PostgreSQL ###########################################
  postgres:
    image: postgres:alpine
    command: postgres
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  ### ElasticSearch ########################################
  elasticsearch:
    image: registry.gitlab.com/flagstudio/laraflag:elasticsearch-7.6.2
    volumes:
      - ${ELASTICSEARCH_CONFIG_PATH}:/usr/share/elasticsearch/data
    environment:
      - cluster.name=laradock-cluster
      - node.name=laradock-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=laradock-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "127.0.0.1:${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
      - "127.0.0.1:${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"

  elastichq:
    image: elastichq/elasticsearch-hq
    ports:
      - ${ELASTICHQ_PORT}:5000
    depends_on:
      - elasticsearch
