version: '3'

services:

    ### PHP-FPM + Caddy ##############################################
    app:
      image: registry.gitlab.com/flagstudio/${COMPOSE_PROJECT_NAME}:latest
      ports:
        - "8080:8080"
      volumes:
        - ./.env:/var/www/.env
        - ./storage:/var/www/storage

### MySQL ################################################
    mysql:
      build:
        context: ./docker/mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - "127.0.0.1:${MYSQL_PORT}:3306"
      restart: always

  ### SSL proxy (Caddy Server) #########################################
    ssl:
      image: registry.gitlab.com/flagstudio/laraflag:ssl-base
      ports:
        - "443:443"
        - "80:80"
      volumes:
        - ./Caddyfile_SSL:/etc/Caddyfile
