version: '3'

services:

  ### PHP-FPM + Caddy ##############################################
  app:
    build:
      args:
        - NOVA_USERNAME=${NOVA_USERNAME}
        - NOVA_PASSWORD=${NOVA_PASSWORD}
      context: .
      dockerfile: docker/app/Dockerfile_local
    image: registry.gitlab.com/flagstudio/${COMPOSE_PROJECT_NAME}:latest # образ, который строим. НЕ ТОТ из которого строимся
    volumes:
      - ./:/var/www
    ports:
      - "8080:8080"

  ### MySQL ################################################
  mysql:
    build:
      context: ./docker/mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:${MYSQL_PORT}:3306"
    restart: always

  ### SSL proxy (Caddy Server) #########################################
  ssl:
    build:
      context: .
      dockerfile: docker/ssl/Dockerfile
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./docker/ssl/Caddyfile_http:/etc/Caddyfile
