version: '3'

services:

### PHP-FPM + Caddy ##############################################
    app:
      build:
        args:
          - PHP_VERSION=7.4
        context: .
        dockerfile: docker/app/Dockerfile
      image: registry.gitlab.com/flagstudio/${COMPOSE_PROJECT_NAME}:latest # образ, который строим. НЕ ТОТ из которого строимся
      ports:
        - "8080:8080"


  ### MySQL ################################################
    mysql:
      build:
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
        context: ./docker/mysql
      environment:
        - TZ=Europe/Moscow
      image: registry.gitlab.com/flagstudio/laraflag:mysql-${MYSQL_VERSION}-base # образ, который строим. НЕ ТОТ из которого строимся
      ports:
        - "127.0.0.1:3306:3306"
