version: '3'

services:

    ### PHP-FPM + Caddy ##############################################
    app:
      image: registry.gitlab.com/flagstudio/${COMPOSE_PROJECT_NAME}:latest
      ports:
        - "8080:8080"
      volumes:
        - ./.env:/var/www/.env
        - ./storage:/var/www/storage

### MySQL ################################################
    mysql:
      image: registry.gitlab.com/flagstudio/laraflag:mysql-5.7-base
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      ports:
        - "127.0.0.1:3306:3306"
      restart: always

  ### SSL proxy (Caddy Server) #########################################
    ssl:
      image: registry.gitlab.com/flagstudio/laraflag:ssl-base
      ports:
        - "443:443"
        - "80:80"
      volumes:
        - ./Caddyfile_SSL:/etc/Caddyfile
