version: '3'

services:

### PHP-FPM + Caddy ##############################################
    app:
      container_name: ${COMPOSE_PROJECT_NAME}_app_prod
      image: registry.gitlab.com/flagstudio/${COMPOSE_PROJECT_NAME}:latest
      ports:
        - "8080:8080"
      volumes:
        - ./.env:/var/www/.env
        - ./storage:/var/www/storage
      restart: unless-stopped

### MySQL ################################################
    mysql:
      image: registry.gitlab.com/flagstudio/laraflag:mysql-5.7-base
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      ports:
        - "127.0.0.1:3306:3306"
      restart: unless-stopped

### SSL proxy (Caddy Server) #########################################
    ssl:
      image: registry.gitlab.com/flagstudio/laraflag:ssl-base
      ports:
        - "443:443"
        - "80:80"
      volumes:
        - ./Caddyfile_SSL:/etc/Caddyfile

### PostgreSQL ###########################################
    postgres:
      image: postgres:alpine
      command: postgres
      environment:
        - POSTGRES_DB=${DB_DATABASE}
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
      volumes:
        - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
      ports:
        - "127.0.0.1:5432:5432"
      restart: unless-stopped

  ### ElasticSearch ########################################
    elasticsearch:
      image: registry.gitlab.com/flagstudio/laraflag:elasticsearch-7.6.2
      volumes:
        - ${ELASTICSEARCH_CONFIG_PATH}:/usr/share/elasticsearch/data
      environment:
        - cluster.name=laradock-cluster
        - node.name=laradock-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - cluster.initial_master_nodes=laradock-node
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - "127.0.0.1:${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
        - "127.0.0.1:${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"

    elastichq:
      image: elastichq/elasticsearch-hq
      ports:
        - 5000:5000
      depends_on:
        - elasticsearch
