version: '3'

services:

### PHP-FPM + Caddy ##############################################
    app:
      container_name: ${COMPOSE_PROJECT_NAME}_app_build
      build:
        args:
          - PHP_VERSION=7.4
          - PHP_FPM_INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
          - PHP_FPM_INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
        context: .
        dockerfile: docker/app/Dockerfile_build
      image: registry.gitlab.com/flagstudio/${COMPOSE_PROJECT_NAME}:latest # образ, который строим. НЕ ТОТ из которого строимся
      ports:
        - "8080:8080"

